version: '3.5'

services:
  app:
    image: ciapp
    build: 
      context: .
      dockerfile: ./build/Dockerfile.ci
      cache_from:
      - type=local,src=/tmp/.ci-compose-cache
      cache_to:
      - type=local,dest=/tmp/.ci-compose-cache-new,mode=max
    environment:
      DEFAULT_DATABASE_URL: "postgres://user:user@postgres:5432/app?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  test:
    image: ciapp
    environment:
      TEST_SERVER_BASE_URL: "http://app:8080"
    command: make e2e
    depends_on:
      - app

  postgres:
    build:
      context: .
      dockerfile: ./build/Dockerfile.cidb
      cache_from:
      - type=local,src=/tmp/.ci-compose-cache
      cache_to:
      - type=local,dest=/tmp/.ci-compose-cache-new,mode=max
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /data/postgres
      POSTGRES_DB: app
    tmpfs:
      - /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  
