name: ci
on:
  pull_request:
    branches:    
      - main
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ci
      - run: make ci_down
        
