name: ci
on:
  pull_request:
    branches:    
      - main
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "git checkout"
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.ci-docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-cache
      - name: "Run CI docker compose"
        run: make ci
      - name: "Clean containers"
        run: make ci_down
      - name: Move cache
        run: |
          rm -rf /tmp/.ci-docker-cache
          mv /tmp/.ci-docker-cache-new /tmp/.ci-docker-cache        