name: ci
on:
  pull_request:
    branches:    
      - main
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:15-alpine"
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
          POSTGRES_DB: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: |
          go mod tidy
          make build
      - run: ./out/app
        env:
          DEFAULT_DATABASE_URL: "postgres://user:user@postgres:5432/app?sslmode=disable"
      - run: make e2e
        