name: ci
on:
  pull_request:
    branches:    
      - main
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "git checkout"
        uses: actions/checkout@v4
      - name: "Run CI docker compose"
        run: make ci
      - name: "Clean containers"
        run: make ci_down
